language: node_js
services: mongodb
node_js:
  - "12"
  - "13"
cache:
  timeout: 3600
  directories:
  - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=10d2c968d1558bf767f3542fb3715a617c54f41e9433bc573ce9b343f2ed5071
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $TRAVIS_TEST_RESULT
